import type { IntrospectionQuery } from 'graphql';

export const mockIntrospectionResult: IntrospectionQuery = {
  __schema: {
    directives: [],
    mutationType: { kind: 'OBJECT', name: 'Mutation' },
    queryType: { kind: 'OBJECT', name: 'Query' },
    subscriptionType: null,
    types: [
      {
        description: 'The root query type',
        enumValues: null,
        fields: [
          {
            args: [
              {
                defaultValue: null,
                description: 'User ID',
                name: 'id',
                type: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
                },
              },
            ],
            deprecationReason: null,
            description: 'Fetch a user by ID',
            isDeprecated: false,
            name: 'user',
            type: {
              kind: 'OBJECT',
              name: 'User',
              ofType: null,
            },
          },
          {
            args: [
              {
                defaultValue: '10',
                description: 'Max results',
                name: 'limit',
                type: { kind: 'SCALAR', name: 'Int', ofType: null },
              },
            ],
            deprecationReason: null,
            description: 'Fetch all users',
            isDeprecated: false,
            name: 'users',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'OBJECT', name: 'User', ofType: null },
                },
              },
            },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Fetch all posts',
            isDeprecated: false,
            name: 'posts',
            type: {
              kind: 'LIST',
              name: null,
              ofType: { kind: 'OBJECT', name: 'Post', ofType: null },
            },
          },
          {
            args: [],
            deprecationReason: 'Use newField instead',
            description: 'A deprecated field',
            isDeprecated: true,
            name: 'oldField',
            type: { kind: 'SCALAR', name: 'String', ofType: null },
          },
        ],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: 'Query',
        possibleTypes: null,
      },
      {
        description: 'The root mutation type',
        enumValues: null,
        fields: [
          {
            args: [
              {
                defaultValue: null,
                description: 'User input',
                name: 'input',
                type: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'INPUT_OBJECT', name: 'CreateUserInput', ofType: null },
                },
              },
            ],
            deprecationReason: null,
            description: 'Create a new user',
            isDeprecated: false,
            name: 'createUser',
            type: {
              kind: 'OBJECT',
              name: 'User',
              ofType: null,
            },
          },
          {
            args: [
              {
                defaultValue: null,
                description: 'User ID to delete',
                name: 'id',
                type: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
                },
              },
            ],
            deprecationReason: null,
            description: 'Delete a user',
            isDeprecated: false,
            name: 'deleteUser',
            type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
          },
        ],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: 'Mutation',
        possibleTypes: null,
      },
      {
        description: 'A user in the system',
        enumValues: null,
        fields: [
          {
            args: [],
            deprecationReason: null,
            description: null,
            isDeprecated: false,
            name: 'id',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
            },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'The user display name',
            isDeprecated: false,
            name: 'name',
            type: { kind: 'SCALAR', name: 'String', ofType: null },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'The user email',
            isDeprecated: false,
            name: 'email',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Posts by this user',
            isDeprecated: false,
            name: 'posts',
            type: {
              kind: 'LIST',
              name: null,
              ofType: { kind: 'OBJECT', name: 'Post', ofType: null },
            },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'User role',
            isDeprecated: false,
            name: 'role',
            type: { kind: 'ENUM', name: 'UserRole', ofType: null },
          },
        ],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: 'User',
        possibleTypes: null,
      },
      {
        description: 'A blog post',
        enumValues: null,
        fields: [
          {
            args: [],
            deprecationReason: null,
            description: null,
            isDeprecated: false,
            name: 'id',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
            },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Post title',
            isDeprecated: false,
            name: 'title',
            type: { kind: 'SCALAR', name: 'String', ofType: null },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Post body content',
            isDeprecated: false,
            name: 'body',
            type: { kind: 'SCALAR', name: 'String', ofType: null },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Post author',
            isDeprecated: false,
            name: 'author',
            type: { kind: 'OBJECT', name: 'User', ofType: null },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Post comments',
            isDeprecated: false,
            name: 'comments',
            type: {
              kind: 'LIST',
              name: null,
              ofType: { kind: 'OBJECT', name: 'Comment', ofType: null },
            },
          },
        ],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: 'Post',
        possibleTypes: null,
      },
      {
        description: 'A comment on a post',
        enumValues: null,
        fields: [
          {
            args: [],
            deprecationReason: null,
            description: null,
            isDeprecated: false,
            name: 'id',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
            },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Comment text',
            isDeprecated: false,
            name: 'text',
            type: { kind: 'SCALAR', name: 'String', ofType: null },
          },
          {
            args: [],
            deprecationReason: null,
            description: 'Comment author',
            isDeprecated: false,
            name: 'author',
            type: { kind: 'OBJECT', name: 'User', ofType: null },
          },
        ],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: 'Comment',
        possibleTypes: null,
      },
      {
        description: 'Input for creating a user',
        enumValues: null,
        fields: null,
        inputFields: [
          {
            defaultValue: null,
            description: 'User name',
            name: 'name',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          },
          {
            defaultValue: null,
            description: 'User email',
            name: 'email',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          },
          {
            defaultValue: '"USER"',
            description: 'User role',
            name: 'role',
            type: { kind: 'ENUM', name: 'UserRole', ofType: null },
          },
        ],
        interfaces: null,
        kind: 'INPUT_OBJECT',
        name: 'CreateUserInput',
        possibleTypes: null,
      },
      {
        description: 'Available user roles',
        enumValues: [
          {
            deprecationReason: null,
            description: 'Administrator',
            isDeprecated: false,
            name: 'ADMIN',
          },
          {
            deprecationReason: null,
            description: 'Regular user',
            isDeprecated: false,
            name: 'USER',
          },
          {
            deprecationReason: null,
            description: 'Moderator',
            isDeprecated: false,
            name: 'MODERATOR',
          },
        ],
        fields: null,
        inputFields: null,
        interfaces: null,
        kind: 'ENUM',
        name: 'UserRole',
        possibleTypes: null,
      },
      {
        description: 'Built-in String scalar',
        enumValues: null,
        fields: null,
        inputFields: null,
        interfaces: null,
        kind: 'SCALAR',
        name: 'String',
        possibleTypes: null,
      },
      {
        description: 'Built-in Int scalar',
        enumValues: null,
        fields: null,
        inputFields: null,
        interfaces: null,
        kind: 'SCALAR',
        name: 'Int',
        possibleTypes: null,
      },
      {
        description: 'Built-in Float scalar',
        enumValues: null,
        fields: null,
        inputFields: null,
        interfaces: null,
        kind: 'SCALAR',
        name: 'Float',
        possibleTypes: null,
      },
      {
        description: 'Built-in Boolean scalar',
        enumValues: null,
        fields: null,
        inputFields: null,
        interfaces: null,
        kind: 'SCALAR',
        name: 'Boolean',
        possibleTypes: null,
      },
      {
        description: 'Built-in ID scalar',
        enumValues: null,
        fields: null,
        inputFields: null,
        interfaces: null,
        kind: 'SCALAR',
        name: 'ID',
        possibleTypes: null,
      },
      // Built-in introspection types that should be filtered out
      {
        description: 'GraphQL Schema introspection type',
        enumValues: null,
        fields: [],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: '__Schema',
        possibleTypes: null,
      },
      {
        description: 'GraphQL Type introspection type',
        enumValues: null,
        fields: [],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: '__Type',
        possibleTypes: null,
      },
      {
        description: 'GraphQL Field introspection type',
        enumValues: null,
        fields: [],
        inputFields: null,
        interfaces: [],
        kind: 'OBJECT',
        name: '__Field',
        possibleTypes: null,
      },
    ],
  },
} as unknown as IntrospectionQuery;
