import type { IntrospectionQuery } from 'graphql';

export const mockIntrospectionResult: IntrospectionQuery = {
  __schema: {
    queryType: { name: 'Query', kind: 'OBJECT' },
    mutationType: { name: 'Mutation', kind: 'OBJECT' },
    subscriptionType: null,
    types: [
      {
        kind: 'OBJECT',
        name: 'Query',
        description: 'The root query type',
        fields: [
          {
            name: 'user',
            description: 'Fetch a user by ID',
            args: [
              {
                name: 'id',
                description: 'User ID',
                type: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
                },
                defaultValue: null,
              },
            ],
            type: {
              kind: 'OBJECT',
              name: 'User',
              ofType: null,
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'users',
            description: 'Fetch all users',
            args: [
              {
                name: 'limit',
                description: 'Max results',
                type: { kind: 'SCALAR', name: 'Int', ofType: null },
                defaultValue: '10',
              },
            ],
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'OBJECT', name: 'User', ofType: null },
                },
              },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'posts',
            description: 'Fetch all posts',
            args: [],
            type: {
              kind: 'LIST',
              name: null,
              ofType: { kind: 'OBJECT', name: 'Post', ofType: null },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'oldField',
            description: 'A deprecated field',
            args: [],
            type: { kind: 'SCALAR', name: 'String', ofType: null },
            isDeprecated: true,
            deprecationReason: 'Use newField instead',
          },
        ],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'OBJECT',
        name: 'Mutation',
        description: 'The root mutation type',
        fields: [
          {
            name: 'createUser',
            description: 'Create a new user',
            args: [
              {
                name: 'input',
                description: 'User input',
                type: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'INPUT_OBJECT', name: 'CreateUserInput', ofType: null },
                },
                defaultValue: null,
              },
            ],
            type: {
              kind: 'OBJECT',
              name: 'User',
              ofType: null,
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'deleteUser',
            description: 'Delete a user',
            args: [
              {
                name: 'id',
                description: 'User ID to delete',
                type: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
                },
                defaultValue: null,
              },
            ],
            type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
        ],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'OBJECT',
        name: 'User',
        description: 'A user in the system',
        fields: [
          {
            name: 'id',
            description: null,
            args: [],
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'name',
            description: 'The user display name',
            args: [],
            type: { kind: 'SCALAR', name: 'String', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'email',
            description: 'The user email',
            args: [],
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'posts',
            description: 'Posts by this user',
            args: [],
            type: {
              kind: 'LIST',
              name: null,
              ofType: { kind: 'OBJECT', name: 'Post', ofType: null },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'role',
            description: 'User role',
            args: [],
            type: { kind: 'ENUM', name: 'UserRole', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
        ],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'OBJECT',
        name: 'Post',
        description: 'A blog post',
        fields: [
          {
            name: 'id',
            description: null,
            args: [],
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'title',
            description: 'Post title',
            args: [],
            type: { kind: 'SCALAR', name: 'String', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'body',
            description: 'Post body content',
            args: [],
            type: { kind: 'SCALAR', name: 'String', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'author',
            description: 'Post author',
            args: [],
            type: { kind: 'OBJECT', name: 'User', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'comments',
            description: 'Post comments',
            args: [],
            type: {
              kind: 'LIST',
              name: null,
              ofType: { kind: 'OBJECT', name: 'Comment', ofType: null },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
        ],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'OBJECT',
        name: 'Comment',
        description: 'A comment on a post',
        fields: [
          {
            name: 'id',
            description: null,
            args: [],
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'ID', ofType: null },
            },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'text',
            description: 'Comment text',
            args: [],
            type: { kind: 'SCALAR', name: 'String', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
          {
            name: 'author',
            description: 'Comment author',
            args: [],
            type: { kind: 'OBJECT', name: 'User', ofType: null },
            isDeprecated: false,
            deprecationReason: null,
          },
        ],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'INPUT_OBJECT',
        name: 'CreateUserInput',
        description: 'Input for creating a user',
        fields: null,
        inputFields: [
          {
            name: 'name',
            description: 'User name',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            defaultValue: null,
          },
          {
            name: 'email',
            description: 'User email',
            type: {
              kind: 'NON_NULL',
              name: null,
              ofType: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            defaultValue: null,
          },
          {
            name: 'role',
            description: 'User role',
            type: { kind: 'ENUM', name: 'UserRole', ofType: null },
            defaultValue: '"USER"',
          },
        ],
        interfaces: null,
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'ENUM',
        name: 'UserRole',
        description: 'Available user roles',
        fields: null,
        inputFields: null,
        interfaces: null,
        enumValues: [
          { name: 'ADMIN', description: 'Administrator', isDeprecated: false, deprecationReason: null },
          { name: 'USER', description: 'Regular user', isDeprecated: false, deprecationReason: null },
          { name: 'MODERATOR', description: 'Moderator', isDeprecated: false, deprecationReason: null },
        ],
        possibleTypes: null,
      },
      {
        kind: 'SCALAR',
        name: 'String',
        description: 'Built-in String scalar',
        fields: null,
        inputFields: null,
        interfaces: null,
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'SCALAR',
        name: 'Int',
        description: 'Built-in Int scalar',
        fields: null,
        inputFields: null,
        interfaces: null,
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'SCALAR',
        name: 'Float',
        description: 'Built-in Float scalar',
        fields: null,
        inputFields: null,
        interfaces: null,
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'SCALAR',
        name: 'Boolean',
        description: 'Built-in Boolean scalar',
        fields: null,
        inputFields: null,
        interfaces: null,
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'SCALAR',
        name: 'ID',
        description: 'Built-in ID scalar',
        fields: null,
        inputFields: null,
        interfaces: null,
        enumValues: null,
        possibleTypes: null,
      },
      // Built-in introspection types that should be filtered out
      {
        kind: 'OBJECT',
        name: '__Schema',
        description: 'GraphQL Schema introspection type',
        fields: [],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'OBJECT',
        name: '__Type',
        description: 'GraphQL Type introspection type',
        fields: [],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
      {
        kind: 'OBJECT',
        name: '__Field',
        description: 'GraphQL Field introspection type',
        fields: [],
        inputFields: null,
        interfaces: [],
        enumValues: null,
        possibleTypes: null,
      },
    ],
    directives: [],
  },
} as unknown as IntrospectionQuery;
